export const AUTH_LOADING = 'AUTH_LOADING'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const POSTS_LOADING = 'POSTS_LOADING'
export const POSTS_SUCCESS = 'POSTS_SUCCESS'
export const POSTS_ERROR = 'POSTS_ERROR'
export const POSTS_RESET = 'POSTS_RESET'

export const ADD_COMMENT_LOADING = 'ADD_COMMENT_LOADING'
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'
export const ADD_COMMENT_ERROR = 'ADD_COMMENT_ERROR'
export const ADD_COMMENT_RESET = 'ADD_COMMENT_RESET'
